### ISSUE TITLE
Freyja covariants returns empty output

### ISSUE THREAD

**Issue by Krannich479** [andersen-lab/Freyja#298]
## Describe the situation
I have a bam file of aligned reads and after processing it with `frayja covariants` I get an **empty file** (covariants.tsv) when I strongly expect co-occurring variants in many of the reads. The set of reads is synthetic, but fairly realistic data. It's an equimolar mixed sample of two SARS-CoV-2 strains. The IGV screenshot below indicates what I'd expect, i.e. multiple SNVs with 0.5 variant allele frequency.

<img width="1904" height="582" alt="Image" src="https://github.com/user-attachments/assets/85ac3e10-2fe4-4f4d-95b6-5ee957f707ad" />

Is there anything I apparently overlook or I am doing wrong?

## To Reproduce
Run setups I tried:
1. Run plain: `$ freyja covariants ../../mixture_31/mapping.bam.tagged.bam`
2. Run advanced: `freyja covariants --min_count 3 --min_quality 15 --ref-genome ../../MN908947.3.fasta ../../mixture_31/mapping.bam.tagged.bam 21563 25384`

and many combinations of parameters between 1. and 2.

## Expected behavior
I expected a non-empty set of co-occurring mutations from the `freyja covariants` module.

## Output
```
$ freyja covariants --min_count 3 --min_quality 15 --ref-genome ../../MN908947.3.fasta ../../mixture_31/mapping.bam.tagged.bam 21563 25384
covariants: Output saved to covariants.tsv
```
The saved TSV file is empty (header only).
```
Covariants      Count   Max_count       Freq    Coverage_start  Coverage_end
```

**Additional info (please include the following information, if applicable):**
 - OS: Ubuntu 22.04.5 LTS
 - Freyja version: freyja-2.0.1 (from bioconda)

**Comment by dylanpilz** [comment]
As it turns out, I've only tested `covar` using [this](https://github.com/andersen-lab/covar/blob/master/tests/data/NC_045512_Hu-1.gff) annotation file. I pushed a small fix that makes it work with the GFF you provided. If you could clone and install it from the [repo](https://github.com/andersen-lab/covar) and verify it's working that would be appreciated.

As for why annotation files are required to begin with, I chose to keep things simple for the first pass of the tool, though I would be open to making them optional in the future. Currently, `covar` only calls mutations in genes, so it would have to be expanded to call intergenic mutations since we don't have gene regions, but it should be fairly straightforward to implement.

**Comment by Krannich479** [comment]
Thanks for the fix. And for the first time, I get _something_ out of `covar` using your latest commit. I was testing parameters a bit and here is what I got out of it. Note that #lines=2 means empty file (header + one empty line).
```bash
# test as recommended to begin with
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 0 -d 1 -f 0 | wc -l
114

# test quality
$ovar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 0 -d 1 -f 0.001 | wc -l
114
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 5 -d 1 -f 0.001 | wc -l
114
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 10 -d 1 -f 0.001 | wc -l
114
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 20 -d 1 -f 0.001 | wc -l
114

#test frequency
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 20 -d 1 -f 0.01 | wc -l
114
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 20 -d 1 -f 0.1 | wc -l
2

# test depth
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 0 -d 2 -f 0.001 | wc -l
2
$covar -i mapping.bam.tagged.clean.bam -r ../../MN908947.3.fasta -a ../../MN908947.3.gff3 -q 20 -d 2 -f 0.001 | wc -l
2
```
I **hypothesize**, these results indicate that something about the evidence (mutations) across the read depth is not considered correctly. Using the BAM file under investigation, as soon as more than one read is required for evidence of a mutation the output is empty. This is evident when d=2 but also when f=0.1. The latter is a bit more difficult to spot but let me explain.

<img width="901" height="858" alt="Image" src="https://github.com/user-attachments/assets/85de5e55-71cd-47fb-acc9-ed6640d1e9a8" />

As a preamble, the two highlighted mutations in the screenshot above reside within the S-gene range defined in the GFF file. Both occur on 15 reads in total, 14 times co-occurring on the same read. The read depth at both mutation locations is 31. 
Hence, f=0.1 as a minimum frequency for detection should suffice. However, my hypothesis is that somehow only one read is considered for evidence, i.e. 1/31 = 0.03 which is larger than 0.001 and 0.01 but not 0.1. 

---
- Do I overlook anything in the data? Anything I should look into?
- Does my hypothesis make sense?

**Comment by dylanpilz** [comment]
To your first point, coVar looks at unique mutation clusters observed in a read. For that reason, while G21989T and A22206G are indeed observed in the same cluster 14 times, they are seen in different contexts with other mutations (mostly indels in your sample), causing them to be split into different unique clusters, each with `cluster_depth` 1:

```
nt_mutations	aa_mutations	cluster_depth	total_depth	frequency	coverage_start	coverage_end
T21566-TTG C21575-TTGT T21580C T21581A T21582C T21585-G C21588-A C21614T A21647+CAG T21735G T21737+G C21742T A21743T A21801C C21805A C21806T T21810A G21824-AT T21934+AAG T21937A G21989T G22081T C22082A T22084C G22186-C A22190C T22191G T22196+A T22200G G22201A A22206G	S:DEL3 NA S:V6V S:L7T S:L7T NA NA S:L18F S:INS30Q S:F58R NA S:S60L S:N61F S:D80A S:N81* S:P82* S:V83H NA S:INS125K S:N125R S:V143F S:Q173C S:P174I S:P174I NA S:I210R S:I210R NA S:V213* S:V213* S:D215W	1	16	0.0625	21322	22266
T21363G C21364G T21503+A C21614T T21649-A C21654-TT G21666A A21675+T C21678-TG C21682-A A21684C T21690-C C21697-TCAGTTTT C21707T A21712+T A21713G A21788-C A21801C G21828-T T21835A A21887+T G21989T T22160G A22206G	ORF1b:N2632K ORF1b:P2633A NA S:L18S NA NA S:G35* NA NA NA S:K41T NA NA S:H49Y NA S:T51A NA S:D80S NA S:Y91V NA S:V143W S:Y200G S:D215G	1	16	0.0625	21322	22266
G21989T T22020G A22025C T22027C G22028C A22029T G22030T G22049+C A22053T A22091-TGG A22101+T A22102-GG G22112T G22113A A22115G A22116G T22117A T22118G A22121+T G22131+A T22136+A T22137G G22139C T22191A T22192A A22206G A22280-CTTTACTTG T22516+G A22529-CAG A22656T T22657C T22660G G22813T G22844-A T22848G A22850-C A22852-G G22859C	S:V143F S:M153R S:S155R S:S155R S:E156L S:E156L S:E156L NA S:N164V S:DEL178 NA NA S:G184* S:G184* S:N185G S:N185G S:N185G S:F186V NA NA NA S:F192R S:V193H S:I210Q S:I210Q S:D215C S:DEL241/243 NA S:DEL324 S:Y365V S:Y365V S:S366E S:K417T NA S:F429G NA NA S:V433R	1	15	0.066667	21866	22866
G21989T G22018A A22135-TTTGTG A22206G A22280-CTTTACTTG C22414-A A22534-T T22540G G22610C T22611+A A22614+G C22617+T A22688+C G22813T C22818A A22824G A22832C A22833-ATT	S:V143F S:W152* S:DEL192/193 S:D215G S:DEL241/243 NA NA S:I326M S:V350H NA NA NA NA S:K417C S:A419D S:Y421* S:K424L S:DEL425	1	16	0.0625	21866	22862
G21989T C22088G C22097A T22098A G22100A G22103+C A22206G T22228C A22280-CTTTACTTG T22321A T22322C G22484-TAGAAAA A22495C T22738G A22739G T22741A T22746C T22774+C G22778T A22780T C22783T A22784+G G22813T G22844A A22845G	S:V143F S:L176V S:L179N S:L179N S:E180K NA S:D215* S:A222G S:DEL241/243 S:D253* S:S254L NA S:G311S S:F392L S:T393E S:T393E S:V395S NA S:E406F S:E406F S:V407N NA S:K417G S:D428S S:D428S	1	16	0.0625	21870	22866
G21989T C21997-CACAAAAACA C22009-A A22068+GC A22069+C A22110-G A22115T A22135T A22146-G A22155T T22156G T22196+A T22200G T22204G A22206G C22211G C22212T T22213G T22260G A22265+C T22266A G22272+T C22277T A22279-ACTTTACT T22288-G A22300G T22304G A22374C C22376-CTAG G22381-A T22384G G22494+A C22498-T T22501+G A22504C C22509-T G22592+T C22594G A22622G G22627-AAGA G22813T T22831A C22839A A22840C G22844T T22846G T22847A	S:V143F NA NA NA NA NA S:N185C S:E191S NA S:D198M S:D198M NA S:V213C S:R214R S:D215G S:P217V S:P217V S:P217V S:I233R NA S:I235Q NA S:Q239W NA NA S:R246L S:Y248G S:Q271S NA NA S:T274P NA NA NA S:Q314D NA NA S:A344L S:N354D NA S:K417H S:Y423E S:P426Y S:P426Y S:D428L S:D428L S:F429T	1	16	0.0625	21866	22866
G21989T A22007G A22130+GG A22134+T T22136+GACA T22142G T22143G A22149-T A22151-T A22206G C22208-TCCCT G22216-GGT T22220C T22223A G22225+A T22229-TAGA C22236G A22265C A22280-CTTTACTTG A22330T C22572G A22590-C C22596T T22603-G A22614-T G22620C G22621A A22622T G22813T G22817A C22818A T22819C A22824C T22831-A T22863A	S:V143F S:N149D NA NA NA S:F194G S:F194G NA NA S:D215S NA S:DEL219 S:F220P S:S221R NA NA S:P225R S:I235L S:DEL241/243 S:S256I S:P337S NA S:T345L NA NA S:W353S S:W353S S:N354L S:K417N S:A419N S:A419N S:A419N S:Y421S NA S:I434D	1	14	0.071429	21866	22866
G21523-TTATT C21530-TAGTGATG C21541A G21586-CCA C21590G T21591-AG T21596G A21599T G21600A T21601A C21614T C21622A A21801C T21861A C21977G C21978G G21989T T22020C G22037-T C22044A A22206G T22213-CAG G22218T T22219+A	NA NA ORF1b:L2692I S:DEL9 S:L10V NA S:S12A S:S13* S:S13* S:S13* S:L18F S:T20T S:D80A S:I100K S:P139G S:P139G S:V143F S:M153T NA S:S161Y S:D215G S:DEL218 S:G219V NA	1	16	0.0625	21322	22266
G21520T C21575-T G21578-TTTT T21585-G C21614T C21636T A21643-T A21645-C T21667+GGAA A21801C A21902-C G21907+T C21909T C21910A C21911T G21989T A22182T C22183-A A22206G	ORF1b:V2685F NA NA NA S:L18F S:P25L NA NA NA S:D80A NA NA S:S116L S:S116L S:L117C S:V143W S:H207L NA S:D215C	1	16	0.0625	21322	22266
G21351A A21400-GT A21404+TC T21500A T21585-G C21614T A21749C G21761C C21762A T21765G A21766G C21767T C21772-T A21801C G21989T G22051A A22167T C22181-ACA G22186T C22188-T T22191G A22206G A22234T	ORF1b:W2628* NA NA ORF1b:I2678* NA S:L18F S:T63L S:A67Q S:A67Q S:I68R S:I68R S:H69Y NA S:D80S S:V143L S:A163V S:K202L S:DEL208 S:T208T NA S:I210R S:D215G S:E224Y	1	16	0.0625	21322	22266
C21930-T A21936G G21938+T T21942A T21943C G21989T G22100T A22101G A22130-GGG A22155-TG T22160G A22206G A22279-ACTT A22285-CTTGC C22425-T A22431-C T22465C G22567A C22570+T C22571T C22572A G22577-GT G22580C A22590G C22591T C22593A C22596A G22604T G22676T T22684C T22685C C22686G C22716A G22727-A C22730A G22734+C G22813T T22816-G	NA S:N125S NA S:V127Y S:V127Y S:V143C S:E180* S:E180* S:DEL191 NA S:Y200V S:D215* NA NA NA NA S:C301V S:L335L NA S:P337Y S:P337Y NA S:E340L S:N343C S:N343C S:A344K S:T345Q S:A348L S:A372S S:F374H S:S375R S:S375R S:T385Q NA S:L390I NA S:K417G NA	1	16	0.0625	21866	22866
C21335A T21339C C21342G A21343-T A21345-T T21347C G21375-TC C21386-TTTAT A21436-T G21438-TCT G21448-A C21614T T21657-CA G21663-T T21669C T21679+G A21801C G21989T C22050G G22051C A22052T G22154+A T22156+C G22158A A22206G T22238+A	ORF1b:A2623E ORF1b:N2624N ORF1b:Y2625* NA NA ORF1b:F2627S NA NA NA ORF1b:DEL2658 NA S:L18F NA NA S:V36A NA S:D80S S:V143C S:A163C S:A163C S:N164* NA NA S:G199D S:D215R NA	1	16	0.0625	21322	22266
C21335A A21336T A21337G T21439G C21440T T21442+GG A21446T C21614T T21633-A T21640+G A21801C G21989T C22006-A A22008T G22014A T22016+G A22110-G A22206G	ORF1b:A2623D ORF1b:A2623D ORF1b:N2624D ORF1b:S2658V ORF1b:S2658V NA ORF1b:K2660L S:L18F NA NA S:D80S S:V143C NA S:N149I S:S151K NA NA S:D215G	1	16	0.0625	21322	22266
A21892C G21893A T21896A G21901C G21987C G21989T G22022C T22153A A22194+T G22201-CGT G22205-A A22255+G T22276G A22280-CTTTACTTG G22316+A G22317+CCA T22318G T22463G T22465-A T22470+A G22471A A22600+C C22664G G22813T	S:L110F S:D111N S:S112T S:K113N S:G142A S:V143F S:E154Q S:I197I NA S:DEL214 NA NA S:F238G S:DEL241/243 NA S:INS253P S:G252T S:C301A NA NA S:L303* NA S:L368V S:K417N	1	16	0.0625	21866	22866
A21505+T A21507G C21614T C21629-AA A21634+TAG C21638G A21801C A21849-G A21852-GT C21914+CT G21989T G22035C A22036T G22037A T22039A T22040G T22189-A A22194C T22196C T22197-AGTGC A22206G	NA ORF1b:R2680* S:L18S NA S:INS25* S:P26A S:D80A NA NA NA S:V143L S:R158A S:R158A S:V159I S:V159I S:Y160G NA S:N211P S:L212L NA S:D215G	1	16	0.0625	21322	22266
```

Regarding your point concerning read depth, we calculate `total_depth` here by considering the total number of read **pairs** in the sample that span the observed cluster of mutations, which explains why we see 16 instead of 31 for the depth in this case. 

Let me know if I can help clear anything else up

**Comment by Krannich479** [comment]
Thanks for the detailed info. What I still not fully understand is how a run e.g. using `-q 10 -d 10 -f 0.001` as parameters is not clustering this co-occurring variant pair only. Maybe it is a misconception of mine about how the clusters are formed. I thought with all constraints met through the parameters, there will be only these two co-occurring variants left in a cluster (of reads).

I inspect the clusters and see depth=1 everywhere so I guess it is about that. Is it a problem for the `total_depth` count that we deal with long (unpaired) reads here?

**Comment by Krannich479** [comment]
Sure. The sample is an equimolar _in-silico_ mixture of COVID Alpha and Beta strains. We then simulated ONT long reads from this mixed sample using NanoSim (trained on R10.4.1 ONT reads). Data is fairly realistic imho.

Looking into the [zoomed screenshot above](https://github.com/andersen-lab/Freyja/issues/298#issuecomment-3360096027) I was wondering

1. what are the erroneous indels you refer to?
2. why do you compute quality scores for indels (because usually they dont have one)?
3. and why do they affect the detection of co-variants (that are not even on the same haplotype)?

Let me elaborate some more. 

1. The reads do have some indel sequencing errors. But from what I can tell, none of them cluster in a fashion that results in a variant allele frequency that is relevant for any misinterpretation. The only pattern of an indel that is an actual indel (and not a sequencing error) is 21,991-21,993. That's an actual variant allele.
2. I do not yet understand why you force the program to compute a quality score for an indel. To the best of my knowledge, indels do not have a quality score and I believe the algorithm doesn't strictly need one. For the case of INS and DEL the program could just work using frequency and depth alone. Missing DEL bases in a read do not have a quality (you use [neighbor bases](https://github.com/andersen-lab/covar/blob/9263177a94ca5709d8fb3b22907cef9c22648158/src/call_variants.rs#L77)). For the INS case you use [either the INS' minimum base quality or 0](https://github.com/andersen-lab/covar/blob/9263177a94ca5709d8fb3b22907cef9c22648158/src/call_variants.rs#L68C29-L68C122), which I think has also pitfalls.
3. Most importantly: I do not understand why indels are an issue at all (might be my lack of understanding of your algorithm). In my mixture sample, the haplotype with the two mutations has multiple reads with no indel between the mutations at all. Even when using reads with indels: why does that affect the detection of co-occurring SNP mutations at completely unrelated locations? The haplotype with the systematic 3nt deletion has no co-occurring SNP mutations (in the screenshot frame) so it'd be okay to not report any. Overall, what I am trying to say is that G21989T and A22206G should be clearly detectable without indels in the reads being a problem. Their signal is extremely obvious. Even more so for any depth >1.

Let me try another example 😃 
In the screenshot below, from the same data (BAM file), the alignments show an absolutely clear co-occurrence of SNPs. No significant indel nearby the haplotype defining mutations. Also not detected by covar if d>1.

<img width="1654" height="589" alt="Image" src="https://github.com/user-attachments/assets/d7411b75-8ec4-4b1c-ae0a-65bac58d88a7" />
